# Adjencency matrix
</h2>
one of the way to show graph,
<br>
this implementation is simple type (not weighted),
<br>
but you can use for both directed graph or undirected graph (defualt in undirected)
<h2/>    


# Packages

In [1]:
import numpy as np

## Source

In [45]:
class AdjcencyMatrix:
    def __init__(self, size):
        self.size = size
        V = (size, size)
        self.graph = np.zeros(V)


    def addEdge(self, x, y, x_in_y_out=True):
        if x >= self.size or y >= self.size:
            raise ValueError("vertex does not exist !!")
        
        elif x==y:
            return "Same vertex"

        else:
            if x_in_y_out:
                self.graph[x][y] = 1
            
            else:
                self.graph[x][y] = -1

    def addVertex(self):
        old = self.graph
        self.graph = np.zeros( (self.size + 1, self.size + 1) )
        self.size += 1
        self.graph[:len(self.graph)-1,:len(self.graph)-1] = old[:][:]


    def showGraph(self):
        print( self.graph )

    @property
    def empty(self):
        return int ((self.size ** 2) - sum( sum(self.graph ** 2) ))

    @property
    def vertexes(self):
        return int (self.size)

    @property
    def edges(self):
        return int( (self.size ** 2) - (self.empty))




# Unit Test

In [49]:
Graph = AdjcencyMatrix(5)

Graph.addEdge(1, 2)

Graph.showGraph()

print(Graph.empty)
print(Graph.edges)
print(Graph.vertexes) #same to .size

Graph.addVertex()

Graph.showGraph()

print(Graph.vertexes)


[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
24
1
5
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
6
