# Adjencency matrix
</h2>
one of the way to show graph,
<br>
this implementation is simple type (not weighted),
<br>
but you can use for both directed graph or undirected graph (defualt in undirected)
<h2/>    


# Packages

In [1]:
import numpy as np

## Source

In [61]:
class AdjcencyMatrix:
    def __init__(self, size):
        self.size = size
        V = (size, size)
        self.graph = np.zeros(V)

    def addEdge(self, x, y, x_in_y_out=True):
        if x >= self.size or y >= self.size:
            raise ValueError("vertex does not exist !!")
        
        elif x==y:
            return "Same vertex"

        else:
            if x_in_y_out:
                self.graph[x][y] = 1
            
            else:
                self.graph[x][y] = -1

    def addVertex(self):
        old = self.graph
        new = np.zeros( (self.size + 1, self.size + 1) )
        self.size += 1
        self.graph =  new[:len(new)-1,:len(new)-1] = old[:][:]

        print(old)
        print(new)


    def showGraph(self):
        return self.graph


# Unit Test

In [67]:
Graph = AdjcencyMatrix(5)

Graph.addEdge(1, 2)

# print(Graph.showGraph())

# Graph.addVertex()

# print(Graph.showGraph())

Graph.addVertex()

print(Graph.showGraph())


[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [56]:


a = np.zeros((5,5))

a[1][1] = 1
a[1][2] = 3
a[0][4] = 2

# print(a)


b = np.zeros( (6,6) )

b[:len(b)-1:][:len(b)-1:] = a[:][:]



[[0. 0. 0. 0. 2.]
 [0. 1. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 2. 0.]
 [0. 1. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
